[model]
package = "bonito.crf"

[labels]
labels = [ "N", "A", "C", "G", "T",]

[input]
features = 1

[qscore]
bias = 0.0
scale = 1.0

[encoder]
stride = 5
winlen = 19
scale = 5.0
features = 768
rnn_type = "lstm"
activation = "swish"

[global_norm]
state_len = 5

[training]
command = "train"
training_directory = "/vol/bitbucket/jlq17/dna_archival_storage/bonito/bonito/models/pruned_global_unstructured/trained_996"
config = "/vol/bitbucket/jlq17/dna_archival_storage/bonito/bonito/models/configs/dna_r9.4.1@v3.toml"
directory = "/vol/bitbucket/jlq17/dna_archival_storage/bonito/bonito/models/na_r9.4.1"
device = "cuda"
lr = 0.0005
seed = 25
epochs = 5
batch = 32
chunks = 0
val_chunks = 1000
amp = false
multi_gpu = false
force = false
pretrained = "/vol/bitbucket/jlq17/dna_archival_storage/bonito/bonito/models/pruned_global_unstructured"
weights = "8_1"
func = "<function main at 0x7f2798658430>"
